server:
  #端口号
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    #tomcat的URI编码
    uri-encoding: utf-8

spring:
  application:
    name: express
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 1111

  redis:
    host: 127.0.0.1
    port: 6379
    #密码默认为空
    password: redis
    timeout: 3000  # 连接超时时间
    lettuce:
      shutdown-timeout: 100  #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
      pool:
        time-between-eviction-runs: 100
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 3   # 连接池中的最大空闲连接
        min-idle: 1   # 连接池中的最小空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）

#日志配置
logging:
  level:
    org.springframework: debug

mybatis:
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: spingboot.express.pojo,spingboot.express.dto.*
  global-config:
    #是否控制台 print mybatis-plus 的 LOGO
    banner: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #表前缀
      #      table-prefix: tb_
      #表名、是否使用下划线命名
      table-underline: true
    configuration:
      call-setters-on-nulls: true
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#token验证
jwt:
  id: express_jwt_id
  access:
    token:
      secret: 23456dfhgff98858875fjgsifjghi25212
  refresh:
    secret: w46245643gfhsfhsfgh5546546452f2hg12


#微信端请求获取token
wechat:
  appId: wx1408855333e63f23
  secret: a94fbedbfaf571622398aa4965df0205
  requestUrl: https://api.weixin.qq.com/sns/jscode2session?appid={appId}&secret={secret}&js_code={userCode}&grant_type=authorization_code
