server:
  #端口号
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    #tomcat的URI编码
    uri-encoding: utf-8

spring:
  application:
    name: express
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 15226221250

#日志配置
logging:
  level:
    org.springframework: debug

#mybatis-plus:
#  mapperLocations: classpath:mybatis/**/*Mapper.xml
#    #实体扫描，多个package用逗号或者分号分隔
#    typeAliasesPackage: spingboot.express.pojo

# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql