server:
  #端口号
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    #tomcat的URI编码
    uri-encoding: utf-8

spring:
  application:
    name: express
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: dbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 1111