server:
  #端口号
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    #tomcat的URI编码
    uri-encoding: utf-8

spring:
  application:
    name: express
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 15226221250

#日志配置
logging:
  level:
    org.springframework: debug

mybatis:
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: spingboot.express.pojo
  global-config:
    #是否控制台 print mybatis-plus 的 LOGO
    banner: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #表前缀
      #      table-prefix: tb_
      #表名、是否使用下划线命名
      table-underline: true
    configuration:
      call-setters-on-nulls: true
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jwt:
  id: express_jwt_id
  access:
    token:
      secret: 23456dfhgff98858875fjgsifjghi25212
  refresh:
    secret: w46245643gfhsfhsfgh5546546452f2hg12